wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.31
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.11.4
    t:
      3:
      - 2
      4: 3.11.4
      5: 0.10.31
      8:
      - 5
