name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=1.2.3
  - pip=20.3.3
  - scikit-learn=0.24.1
  - numpy =1.23.4
  - pip:
      - wandb==0.10.21
      - protobuf==3.20.0
